# Generated by Django 2.0.3 on 2018-03-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20180318_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='url',
        ),
        migrations.AddField(
            model_name='item',
            name='content_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
