# Generated by Django 2.0.3 on 2019-01-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='summary',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
