# Generated by Django 2.0.3 on 2019-01-23 03:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_item_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='published_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
